<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<AssemblyName>JudgementCounter</AssemblyName>
		<Description>Real Time Hit Note Judgement Counter</Description>
		<Version>1.0.0</Version>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>
		<TromboneChampDir>G:\SteamLibrary\steamapps\common\TromboneChamp</TromboneChampDir>
		<TromboneTootDir>D:\r2modman\TromboneChamp\profiles\napp</TromboneTootDir>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
		<PackageReference Include="BepInEx.Core" Version="5.*" />
		<PackageReference Include="BepInEx.PluginInfoProps" Version="1.*" />
		<PackageReference Include="UnityEngine.Modules" Version="2019.4.40" IncludeAssets="compile" />
		<PackageReference Include="TromboneChamp.GameLibs" Version="1.30.0" />
		<PackageReference Include="TromboneChamp.BaboonAPI" Version="2.10.0" />
		<PackageReference Include="TromboneChamp.TrombLoader" Version="2.4.3" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
		<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="TootTallyCore">
			<HintPath>$(TromboneTootDir)\BepInEx\plugins\TootTally-TootTallyCore\TootTallyCore.dll</HintPath>
		</Reference>
		<Reference Include="TootTallySettings">
			<HintPath>$(TromboneTootDir)\BepInEx\plugins\TootTally-TootTallySettings\TootTallySettings.dll</HintPath>
		</Reference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(TromboneTootDir)\BepInEx\plugins\n4ppstar-JudgementCounter" />
	</Target>
</Project>